/**
 * @file
 * Pre-renders all MJML email templates for each locale at build time.
 * Outputs static HTML constants so mjml is not needed at runtime.
 * Run automatically as part of the build step.
 */

import { logger } from "@tokistack/logger";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { waitlistConfirmation } from "../src/templates/waitlist-confirmation";

const LOCALES = ["en", "de"] as const;

const waitlistHtml = Object.fromEntries(
  LOCALES.map((locale) => [locale, waitlistConfirmation({ locale }).html]),
);

const content = [
  "// Auto-generated by scripts/prerender-templates.ts — do not edit manually",
  `export const waitlistConfirmationHtml = ${JSON.stringify(waitlistHtml, null, 2)} as const;`,
  "",
].join("\n");

const outDir = path.resolve("src/generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(path.join(outDir, "waitlist-confirmation.ts"), content);

logger.info("Pre-rendered email templates.");
