name: Setup Node.js and pnpm
description: Setup Node.js with pnpm cache and install dependencies

inputs:
  node-version:
    description: "Node.js version to use"
    required: true

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - name: Setup Node.js environment
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
