import { logger } from "@tokistack/logger";
import fs from "node:fs";
import path from "node:path";

const localeDir = path.resolve(import.meta.dirname, "../locales");
const outputPath = path.resolve(import.meta.dirname, "../generated/translation-keys.ts");

const files = fs.readdirSync(localeDir).filter((f: string) => f.endsWith(".json"));

if (files.length === 0) {
  logger.error("No locale JSON files found in %s", localeDir);
  process.exit(1);
}

const locales = new Map<string, Set<string>>();

for (const file of files) {
  const data: Record<string, string> = JSON.parse(fs.readFileSync(path.join(localeDir, file), "utf-8"));
  locales.set(file, new Set(Object.keys(data)));
}

const [referenceFile, referenceKeys] = locales.entries().next().value as [string, Set<string>];
let failed = false;

for (const [file, keys] of locales) {
  if (file === referenceFile) continue;

  const missing = [...referenceKeys].filter((k) => !keys.has(k));
  const extra = [...keys].filter((k) => !referenceKeys.has(k));

  if (missing.length) {
    logger.error("%s is missing keys: %s", file, missing.join(", "));
    failed = true;
  }
  if (extra.length) {
    logger.error("%s has extra keys: %s", file, extra.join(", "));
    failed = true;
  }
}

if (failed) {
  process.exit(1);
}

const keys = [...referenceKeys].sort();
const union = keys.map((k) => `  | "${k}"`).join("\n");

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(
  outputPath,
  `// Auto-generated by validate-translations.ts — do not edit manually.

export type TranslationKey =
${union};
`,
);

logger.info("Validated %d locales, generated %d translation keys.", files.length, keys.length);
